# Generated by Django 3.2.3 on 2021-06-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本'),
        ),
    ]
