# Generated by Django 3.2.3 on 2021-06-12 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEra',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cycle', models.PositiveSmallIntegerField(verbose_name='纪周')),
                ('veins', models.PositiveSmallIntegerField(verbose_name='纪脉')),
                ('point', models.PositiveSmallIntegerField(verbose_name='纪点')),
                ('dimen', models.PositiveSmallIntegerField(verbose_name='纪维')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_time', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(blank=True, editable=False, verbose_name='修改时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 纪元',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStage',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('maturity', models.PositiveSmallIntegerField(choices=[(1, '开始'), (2, '草稿'), (3, '撰写'), (4, '编校'), (5, '定稿')], default=1, verbose_name='阶段')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '人物'), (2, '地点'), (3, '纪元'), (4, '事件')], default=4, verbose_name='类型')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_time', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(blank=True, editable=False, verbose_name='最近修改时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 故事',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('maturity', models.PositiveSmallIntegerField(choices=[(1, '开始'), (2, '草稿'), (3, '撰写'), (4, '编校'), (5, '定稿')], default=1, verbose_name='阶段')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, '人物'), (2, '地点'), (3, '纪元'), (4, '事件')], default=4, verbose_name='类型')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now_add=True, verbose_name='最近修改时间')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '故事',
                'verbose_name_plural': '故事',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalplace',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='person',
            name='author',
        ),
        migrations.RemoveField(
            model_name='place',
            name='author',
        ),
        migrations.AddField(
            model_name='era',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='era',
            name='updated_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='修改时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='era',
            name='version',
            field=models.IntegerField(default=1, verbose_name='版本'),
        ),
        migrations.DeleteModel(
            name='HistoricalPerson',
        ),
        migrations.DeleteModel(
            name='HistoricalPlace',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
    ]
