# Generated by Django 3.2.3 on 2021-06-15 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
