# Generated by Django 3.2.3 on 2021-06-12 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20210612_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstage',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='historicalstage',
            name='updated_time',
        ),
    ]
