# Generated by Django 3.2.3 on 2021-06-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20210612_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstage',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='name',
            new_name='title',
        ),
    ]
