# Generated by Django 3.2.3 on 2021-06-14 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_auto_20210614_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstage',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 片断'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['-id'], 'verbose_name': '片断', 'verbose_name_plural': '片断'},
        ),
        migrations.RemoveField(
            model_name='stage',
            name='author',
        ),
        migrations.AddField(
            model_name='historicalstage',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='stage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='创建者'),
            preserve_default=False,
        ),
    ]
