# Generated by Django 3.2.3 on 2021-06-14 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0005_auto_20210614_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='author',
            field=models.ManyToManyField(related_name='author_to_user', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
    ]
