# Generated by Django 3.2.3 on 2021-06-14 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0007_alter_stage_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='author',
        ),
        migrations.AddField(
            model_name='stage',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
    ]
