# Generated by Django 3.2.3 on 2021-06-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20210614_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEra',
        ),
    ]
