# Generated by Django 3.2.3 on 2021-06-14 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0009_delete_historicalera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstage',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='owner',
        ),
        migrations.AlterField(
            model_name='stage',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
    ]
