# Generated by Django 3.2.3 on 2021-06-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20210614_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='authors',
        ),
    ]
