# Generated by Django 3.2.3 on 2021-06-14 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0011_remove_stage_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='authors',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
    ]
