# Generated by Django 3.2.3 on 2021-06-14 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0012_stage_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='authors',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL, verbose_name='参与者'),
        ),
    ]
