# Generated by Django 3.2.3 on 2021-06-06 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('maturity', models.PositiveSmallIntegerField(choices=[(1, '开始'), (2, '草稿'), (3, '撰写'), (4, '编辑校对'), (5, '定稿')], default=1, verbose_name='阶段')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '片断',
                'verbose_name_plural': '片断',
                'ordering': ['-id'],
            },
        ),
    ]
