# Generated by Django 3.2.3 on 2021-06-10 00:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stage',
            new_name='Doc',
        ),
    ]
