# Generated by Django 3.2.3 on 2021-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_rename_stage_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='maturity',
            field=models.PositiveSmallIntegerField(choices=[(1, '开始'), (2, '草稿'), (3, '撰写'), (4, '编校'), (5, '定稿')], default=1, verbose_name='阶段'),
        ),
    ]
