site_name: 赛凡链文档
nav:
    - 首页: 首页.md
    - 成为创作者: 成为创作者.md
    - 成为证证人: 成为验证人.md
    - 发展路线图: 发展路线图.md
    - 白皮书: 白皮书.md
    - 贡献文档: 贡献文档.md
copyright: Copyright &copy; 2021 <a href="http://docs.scifanchain.com">赛凡链</a>.
theme: 
  name: 'cosmo'

dev_addr: '127.0.0.1:9000'