site_name: 赛凡链文档
nav:
    - 首页: index.md
    - 成为创作者: be-author.md
    - 成为节点: be-node.md
    - 路线图: road-map.md
    - 蓝皮书: blue-book.md
copyright: Copyright &copy; 2021 <a href="http://docs.scifanchain.com">赛凡链</a>.
theme: 
  name: 'cosmo'

dev_addr: '127.0.0.1:9000'