# Generated by Django 3.2.3 on 2021-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=510, verbose_name='分类名称'),
        ),
    ]
