# Generated by Django 3.2.3 on 2021-06-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20210607_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='website',
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
