# Generated by Django 3.2.3 on 2021-06-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210608_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '显示'), (0, '隐藏')], default=1, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '正常'), (0, '删除'), (2, '冻结')], default=1, verbose_name='状态'),
        ),
    ]
